encoding: UTF-8

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: srcery - Dark Color Scheme
author: srcery team
description: >- # this means to ignore newlines until "baseurl:"
  Preview site for the srcery color scheme.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "github.io" # the base hostname & protocol for your site, e.g. http://example.com

highlighter: rouge
# # Build settings
markdown: kramdown
# https://github.com/github/pages-gem/issues/482
theme: null
plugins:
  # - jekyll-feed
  - jekyll-seo-tag
  - jemoji

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - assets/images/title.png
  - config
  - node_modules
  - package-lock.json
  - package.json
  - src
  - vendor
